# Generated by Django 5.1.6 on 2025-03-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expensetracker.budget'),
        ),
    ]
