# Generated by Django 5.1.6 on 2025-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0010_alter_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('M', 'MainIncome'), ('S', 'SideIncome'), ('G', 'Gift')], default='', max_length=1),
        ),
    ]
